#!/usr/bin/env python3
"""Ensure resumable Vibe state before compaction."""

from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts/vibe"))

from policy import load_hook_event

CHECKPOINT_DIR = ROOT / ".context/checkpoints"
MAX_AUTO_CHECKPOINTS = 10


def read_json(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    if isinstance(data, dict):
        return data
    return {}


def latest_verification_summary() -> str:
    path = ROOT / ".context/verification.jsonl"
    if not path.exists():
        return "No verification record found."
    for line in reversed(path.read_text(encoding="utf-8", errors="replace").splitlines()):
        if not line.strip():
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(record, dict):
            continue
        parts = []
        for key in ("time", "status", "command", "summary"):
            value = record.get(key)
            if value:
                parts.append(f"{key}: {value}")
        return "; ".join(parts) if parts else "Verification record exists."
    return "No parseable verification record found."


def unique_checkpoint_path(now: datetime) -> Path:
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    stem = now.strftime("%Y%m%d-%H%M%S-auto-precompact")
    path = CHECKPOINT_DIR / f"{stem}.md"
    counter = 2
    while path.exists():
        path = CHECKPOINT_DIR / f"{stem}-{counter}.md"
        counter += 1
    return path


def cleanup_auto_checkpoints() -> None:
    auto_checkpoints = sorted(
        CHECKPOINT_DIR.glob("*-auto-precompact*.md"),
        key=lambda path: (path.stat().st_mtime, path.name),
        reverse=True,
    )
    for stale in auto_checkpoints[MAX_AUTO_CHECKPOINTS:]:
        stale.unlink(missing_ok=True)


def write_auto_checkpoint() -> Path:
    state = read_json(ROOT / ".context/state.json")
    now = datetime.now().astimezone()
    path = unique_checkpoint_path(now)
    content = f"""# Vibe Checkpoint: Auto Precompact

Date: {now.isoformat(timespec="seconds")}
Generated by: `.codex/hooks/pre_compact_checkpoint.py`

## Current State

- Current goal: {state.get("current_goal", "unknown")}
- Phase: {state.get("phase", "unknown")}
- Active task: {state.get("active_task", "unknown")}
- Blocked: {state.get("blocked", "unknown")}
- Next action: {state.get("next_action", "unknown")}

## Recovery Pointers

- Plan: `.context/plan.md`
- State: `.context/state.json`
- Verification log: `.context/verification.jsonl`
- PRD: `docs/PRD.md`
- Acceptance criteria: `docs/acceptance.md`

## Last Green Command

```bash
{state.get("last_green_command", "unknown")}
```

## Latest Verification

{latest_verification_summary()}
"""
    path.write_text(content, encoding="utf-8")
    cleanup_auto_checkpoints()
    return path


def block_compaction(missing: list[str]) -> None:
    print(
        json.dumps(
            {
                "continue": False,
                "stopReason": "Missing Vibe base state before compaction.",
                "systemMessage": "Restore Vibe base state before compaction: "
                + ", ".join(missing),
            },
            ensure_ascii=False,
        )
    )


def main() -> int:
    event = load_hook_event()
    if event.get("hook_event_name") not in (None, "PreCompact"):
        return 0
    missing = []
    for rel in [".context/state.json", ".context/plan.md"]:
        if not (ROOT / rel).exists():
            missing.append(rel)
    if missing:
        block_compaction(missing)
        return 0

    checkpoint = write_auto_checkpoint()
    print(
        json.dumps(
            {
                "systemMessage": "Auto-created Vibe checkpoint before compaction: "
                + str(checkpoint.relative_to(ROOT)),
            },
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
